[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
tinyvec = "1.8.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "day1"
harness = false

[[bench]]
name = "day2"
harness = false

[[bench]]
name = "day3"
harness = false
